In [5]:
import numpy as np

In [5]:
a=np.array([1,2,3])
a

[1 2 3]


In [6]:
a[0]

1

In [7]:
a.ndim

1

In [8]:
a.itemsize

4

In [9]:
a.shape

(3,)

In [11]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 2)

In [14]:
a.itemsize

4

In [17]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [18]:
a.itemsize

8

In [19]:
a.shape

(3, 2)

In [25]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)
a

C:\Users\mahes\AppData\Local\Temp\ipykernel_17160\3600199659.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
l=range(5)
l

range(0, 5)

In [13]:
np.arange(5)

[0 1 2 3 4]


In [16]:
print('concatenation example')
print(np.char.add('hello','abc'))
print(np.char.add(['hello','hi'],['abc','xyz']))

concatenation example
helloabc
['helloabc' 'hixyz']


In [19]:
print(np.char.multiply('hello ',3))

hello hello hello 


In [23]:
print(np.char.center('hello',20,fillchar='-'))

-------hello--------


In [24]:
print(np.char.capitalize('hello world'))

Hello world


In [25]:
print(np.char.title('how are you doing?'))

How Are You Doing?


In [27]:
print(np.char.lower(['HELLO','WOrLd']))
print(np.char.lower('HELLO'))

['hello' 'world']
hello


In [28]:
print(np.char.upper(['python','WOrLd']))
print(np.char.upper('Python'))

['PYTHON' 'WORLD']
PYTHON


In [37]:
print(np.char.split("hi how are you?"))
print(np.char.splitlines("hi how\n are\n you ??"))

['hi', 'how', 'are', 'you?']
['hi how', ' are', ' you ??']


In [39]:
print(np.char.strip(['nina','admin','anita'],'a'))

['nin' 'dmin' 'nit']


In [41]:
print(np.char.join([':','-'],['dmy','ymd']))

['d:m:y' 'y-m-d']


In [46]:
print(np.char.replace('he is a good dancer','is','was'))

he was a good dancer
